baseURL: https://lights-and-pause.de
title: Lights And Pause
defaultContentLanguage: 'de'
theme: eternity

params:
  image: /images/banner.png
  logo: logo_weiss_quadratisch.png
  subtitle: ''
  copyright: All rights reserved.
  author: Stefanie Blümer
  dontShowSource: true
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:steffi@lights-and-pause.de'
      landing: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.com/asteffib'
  homepage: /work
  specialPages:
    - work
    - archive
  bypassWelcomePage: true
  disableRadius: true
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: dogs
      url: /tags/dogs/
      weight: 2
    - name: tags
      url: /tags/
      weight: 3
    - name: archive
      url: /tags/archive/
      weight: 4
    - name: about
      url: /about/
      weight: 5
